//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int EmployeeID { get; set; }
        public string User_Login { get; set; }
        public string User_Password { get; set; }
        public Nullable<System.DateTime> Create_Account { get; set; }
        public Nullable<System.DateTime> Last_see { get; set; }
    }
}
